### ISSUE TITLE
Add info about Xephyr grab input

### ISSUE THREAD

**Issue by gregoryprogrammer** [mikar/awmtt#2]
I found at http://awesome.naquadah.org/wiki/Using_Xephyr very helpful information:
"While the Xephyr window has focus, press Control-mod3-shift to have Xephyr grab focus. You will now see that the mouse can't leave the window. If you want Xephyr to let go, press control-shift (note: on some systems it should be RIGHT control-shift)."

I think it is a good idea putting it in README

**Comment by mikar** [comment]
It took me a while but i added that bit to the README. Thanks mate!
