### ISSUE TITLE
Testing custom awesome builds

### ISSUE THREAD

**Issue by iorbitearth** [mikar/awmtt#5]
I'd like to play around with the awesome source and eventually contribute to the project. Do you consider awmtt an appropriate tool for testing custom awesome builds that aren't installed to the system path?

For example, I'm considering forking awmtt and adding an option to specify the path to the awesome binary. Does this seem reasonable?

**Comment by mikar** [comment]
Hey,

I haven't touched awmtt in a long while but that shouldn't be a problem. All awmtt needs is a path to a binary and a path to a configuration file.

Good for you, too. I've been wanting to contribute to Awesome in a meaningful way for quite some time, the obstacle being my pitiful C knowledge.

Have fun

**Comment by mikar** [comment]
Merged
